Update workflow

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -40,7 +40,13 @@ jobs:
         pyright backend/src/
 
     - name: Running tests in Docker Compose
-      run: docker-compose -f backend/tests/functional/docker-compose.yml up -d
+      run: |
+        docker-compose -f backend/tests/functional/docker-compose.yml up -d
+        exit_code=$?
+        if [ $exit_code -ne 0 ]; then
+          echo "Docker Compose failed with exit code $exit_code"
+          exit $exit_code
+        fi
 
     - name: Send Telegram notification on success
       if: ${{ success() }}
